### ISSUE TITLE
Binary usage documentation

### ISSUE THREAD

**Issue by khionu** [inetaf/tcpproxy#13]
If there isn't already documentation for using this as a binary, that is definitely necessary. Not everyone who could use this program for their own use will know how to program. Personally, I don't want to read source code to figure out CLI usage.

If there is documentation for this, it's not linked anywhere I can see

**Comment by bradfitz** [comment]
I see documentation at:

https://github.com/google/tcpproxy/tree/master/cmd/tlsrouter

Is that not sufficient?

**Comment by khionu** [comment]
That is, very much so. That said, it's not linked anywhere. I can open a PR for the README.

**Comment by khionu** [comment]
👍

**Comment by danderson** [comment]
Thank you for the PR!

**Comment by khionu** [comment]
My pleasure. Happy to contribute where I can.

**Comment by micw** [comment]
Hi, I have seen that there's some ACME stuff - and nothing about it in the README. Could you please point out what it does?
Best regards,
Michael.
