### ISSUE TITLE
cant install using go get go.universe.tf/tlsrouter

### ISSUE THREAD

**Issue by odedpriva** [inetaf/tcpproxy#19]
```
ubuntu@ip-10-0-1-115:~$ go get go.universe.tf/tlsrouter
package go.universe.tf/tlsrouter: unrecognized import path "go.universe.tf/tlsrouter" (parse https://go.universe.tf/tlsrouter?go-get=1: no go-import meta tags ())
```

**Comment by bradfitz** [comment]
Yeah, I see a 404 for that. @danderson?

**Comment by danderson** [comment]
Yup, the package got renamed to go.universe.tf/tcpproxy, and when we merged the tlsrouter binary into this repo, we didn't update the docs. Fetching the binary should be `go get go.universe.tf/tcpproxy/tlsrouter`.

**Comment by bradfitz** [comment]
@odedpriva, which docs led you astray? Is there something we forgot to update?

**Comment by odedpriva** [comment]
@bradfitz  using this : https://github.com/google/tcpproxy/blob/master/cmd/tlsrouter/README.md

**Comment by bradfitz** [comment]
Thanks, I'll leave that to Dave to fix.
