### ISSUE TITLE
Wrong module name

### ISSUE THREAD

**Issue by cyd01** [inetaf/tcpproxy#33]
Hello
I used to import your project into mine
```
import (
"github.com/inetaf/tcpproxy"
)
```
Recently you've added [go.mod](https://github.com/inetaf/tcpproxy/commit/2825d768aaaef27e854631354415484406b1bc92) in your project.  
But it seems you've made a wrong module name: `module inet.af/tcpproxy` instead of `module github.com/inetaf/tcpproxy`.

When I `go get` my project I got this error:
```
go get
go get: github.com/inetaf/tcpproxy@none updating to
	github.com/inetaf/tcpproxy@v0.0.0-20210824174053-2e577fef49e2: parsing go.mod:
	module declares its path as: inet.af/tcpproxy
	        but was required as: github.com/inetaf/tcpproxy
```

**Comment by josegonzalez** [comment]
I'm also seeing this, but it appears to work if using `inet.af/tcpproxy/cmd` as the module.

**Comment by yangzhen0512** [comment]
It works if adding `replace` in `go.mod`:
`replace inet.af/tcpproxy v0.0.0-20210824174053-2e577fef49e2 => github.com/inetaf/tcpproxy v0.0.0-20210824174053-2e577fef49e2`

**Comment by bradfitz** [comment]
Yes, import it as `inet.af/tcpproxy/*` instead of the github name.
